import Link from "next/link";
import { ArrowLeft, CalendarDays, ExternalLink, LockKeyhole, Users } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import type { V2Company, V2Project } from "@/lib/v2/types";
import { FinancePanel } from "@/components/v2/finance-panel";
import { ResearchPanel } from "@/components/v2/research-panel";

const tabs = ["summary", "research", "companies", "mail", "finance", "files", "activity"] as const;
const labels = { summary: "Resumen", research: "Investigación", companies: "Empresas", mail: "Correo", finance: "Finanzas", files: "Archivos / Enlaces", activity: "Actividad" };

export function ProjectRoom({ project, companies, activeTab }: { project: V2Project; companies: V2Company[]; activeTab: string }) {
  const tab = tabs.includes(activeTab as (typeof tabs)[number]) ? activeTab as (typeof tabs)[number] : "summary";
  const finance = { goal: project.goal, committed: project.committed, received: project.received, inKind: 0, expenses: 0, netReceived: project.received, remaining: Math.max(0, project.goal - project.committed) };
  return <div className="space-y-6">
    <Link href="/projects" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Volver a proyectos</Link>
    <header className="flex flex-col gap-4 border-b border-border pb-5 lg:flex-row lg:items-end lg:justify-between">
      <div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">{project.name}</h1><Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-700">{project.status === "active" ? "Activo" : project.status === "paused" ? "Pausado" : "Borrador"}</Badge></div><p className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-muted-foreground"><span>{project.institution}</span><span className="flex items-center gap-1.5">{project.accessMode === "shared" ? <Users className="size-3.5" /> : <LockKeyhole className="size-3.5" />}{project.accessMode === "shared" ? "Compartido" : `Personal · ${project.ownerName}`}</span>{project.eventDate ? <span className="flex items-center gap-1.5"><CalendarDays className="size-3.5" />{new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeZone: "America/Santiago" }).format(new Date(`${project.eventDate}T12:00:00-04:00`))}</span> : null}</p></div>
      <Link href="/mail" className={buttonVariants({ variant: "outline" })}>Abrir correo <ExternalLink className="size-4" /></Link>
    </header>
    <nav aria-label="Secciones del proyecto" className="flex flex-wrap gap-1 border-b border-border pb-px">{tabs.map((item) => <Link key={item} href={`/projects/${project.id}?tab=${item}`} aria-current={tab === item ? "page" : undefined} className={`border-b-2 px-3 py-2 text-sm font-medium ${tab === item ? "border-primary text-foreground" : "border-transparent text-muted-foreground hover:text-foreground"}`}>{labels[item]}</Link>)}</nav>
    {tab === "research" ? <ResearchPanel projectId={project.id} /> : tab === "finance" ? <FinancePanel projectId={project.id} initial={finance} /> : tab === "companies" ? <CompaniesPanel companies={companies} /> : <SummaryPanel project={project} companies={companies} />}
  </div>;
}

function SummaryPanel({ project, companies }: { project: V2Project; companies: V2Company[] }) { return <div className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(18rem,0.7fr)]"><section className="rounded-lg border border-border bg-card p-5"><h2 className="text-lg font-semibold">Siguiente mejor acción</h2><p className="mt-2 text-sm text-muted-foreground">{project.nextAction}. La investigación profunda solo se ejecutará después de una aprobación explícita.</p><Link href={`/projects/${project.id}?tab=research`} className={buttonVariants({ className: "mt-5" })}>Revisar investigación</Link><div className="mt-7 border-t border-border pt-5"><h3 className="text-sm font-semibold">Pipeline de empresas</h3><div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4"><SmallMetric label="Identificadas" value={String(companies.length)} /><SmallMetric label="Verificadas" value={String(companies.filter((item) => ["verified", "confirmed"].includes(item.factStatus)).length)} /><SmallMetric label="Con contacto" value={String(companies.filter((item) => item.contactName).length)} /><SmallMetric label="Respondieron" value={String(companies.filter((item) => ["respondió", "decisor"].includes(item.contactQuality)).length)} /></div></div></section><aside className="rounded-lg border border-border bg-card p-5"><h2 className="text-base font-semibold">Contexto del proyecto</h2><dl className="mt-4 space-y-4 text-sm"><div><dt className="text-muted-foreground">Institución</dt><dd className="mt-1 font-medium">{project.institution}</dd></div><div><dt className="text-muted-foreground">Fecha</dt><dd className="mt-1 font-medium">{project.eventDate ?? "Por confirmar"}</dd></div><div><dt className="text-muted-foreground">Siguiente acción</dt><dd className="mt-1 font-medium">{project.nextAction}</dd></div><div><dt className="text-muted-foreground">Acceso</dt><dd className="mt-1 font-medium">{project.accessMode === "shared" ? "Trabajo compartido" : `Personal de ${project.ownerName}`}</dd></div></dl></aside></div>; }
function CompaniesPanel({ companies }: { companies: V2Company[] }) { return <div className="divide-y divide-border overflow-hidden rounded-lg border border-border bg-card">{companies.map((company) => <div key={company.id} className="grid gap-2 p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><strong className="text-sm">{company.name}</strong><p className="text-sm text-muted-foreground">{company.nextAction}</p></div><span className="text-xs text-muted-foreground">{company.contactName ?? "Sin contacto"}</span><Badge variant="outline">Fit {company.fitScore}</Badge></div>)}</div>; }
function SmallMetric({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-semibold tabular-nums">{value}</dd></div>; }
