import { z } from "zod";
import { getAllowedUser } from "@/lib/auth/request";
import { getSupabaseServerClient } from "@/lib/supabase/server";
import { buildFinanceSummary } from "@/lib/v2/domain";

const mutationSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("goal"), fundraisingGoal: z.number().min(0), expenseBudget: z.number().min(0).default(0) }),
  z.object({ type: z.literal("contribution"), kind: z.enum(["cash", "in_kind"]), status: z.enum(["requested", "committed", "received", "declined", "cancelled"]), description: z.string().optional(), requestedValue: z.number().min(0).default(0), committedValue: z.number().min(0).default(0), receivedValue: z.number().min(0).default(0), companyId: z.string().uuid().optional(), contactId: z.string().uuid().optional(), evidenceUrl: z.string().url().optional() }),
  z.object({ type: z.literal("expense"), description: z.string().min(1), category: z.string().optional(), budgetedValue: z.number().min(0).default(0), actualValue: z.number().min(0).default(0), occurredOn: z.string().date().optional(), evidenceUrl: z.string().url().optional() }),
]);

export async function GET(_request: Request, { params }: { params: Promise<{ projectId: string }> }) { const user = await getAllowedUser(); if (!user) return Response.json({ error: "unauthorized" }, { status: 401 }); const supabase = await getSupabaseServerClient(); if (!supabase) return Response.json({ error: "auth_unavailable" }, { status: 503 }); const { projectId } = await params; const [goalResult, contributionResult, expenseResult] = await Promise.all([supabase.from("finance_goals").select("*").eq("project_id", projectId).maybeSingle(), supabase.from("contributions").select("*").eq("project_id", projectId).order("created_at", { ascending: false }), supabase.from("expenses").select("*").eq("project_id", projectId).order("occurred_on", { ascending: false })]); if (goalResult.error || contributionResult.error || expenseResult.error) return Response.json({ error: "forbidden_or_unavailable" }, { status: 403 }); const goal = goalResult.data; const contributions = contributionResult.data ?? []; const expenses = expenseResult.data ?? []; return Response.json({ goal, contributions, expenses, summary: buildFinanceSummary({ goal: Number(goal?.fundraising_goal ?? 0), contributions: contributions.map((item) => ({ kind: item.kind, committedValue: Number(item.committed_value), receivedValue: Number(item.received_value) })), expenses: expenses.map((item) => ({ actualValue: Number(item.actual_value) })) }) }); }

export async function POST(request: Request, { params }: { params: Promise<{ projectId: string }> }) { const user = await getAllowedUser(); if (!user) return Response.json({ error: "unauthorized" }, { status: 401 }); const parsed = mutationSchema.safeParse(await request.json()); if (!parsed.success) return Response.json({ error: "invalid_body" }, { status: 400 }); const supabase = await getSupabaseServerClient(); if (!supabase) return Response.json({ error: "auth_unavailable" }, { status: 503 }); const { projectId } = await params; const { data: project } = await supabase.from("projects").select("workspace_id").eq("id", projectId).single(); if (!project) return Response.json({ error: "forbidden" }, { status: 403 }); const item = parsed.data; let result; if (item.type === "goal") result = await supabase.from("finance_goals").upsert({ workspace_id: project.workspace_id, project_id: projectId, fundraising_goal: item.fundraisingGoal, expense_budget: item.expenseBudget, updated_by: user.id }, { onConflict: "project_id" }).select().single(); else if (item.type === "contribution") result = await supabase.from("contributions").insert({ workspace_id: project.workspace_id, project_id: projectId, kind: item.kind, status: item.status, description: item.description, requested_value: item.requestedValue, committed_value: item.committedValue, received_value: item.receivedValue, company_id: item.companyId, contact_id: item.contactId, evidence_url: item.evidenceUrl, created_by: user.id }).select().single(); else result = await supabase.from("expenses").insert({ workspace_id: project.workspace_id, project_id: projectId, description: item.description, category: item.category, budgeted_value: item.budgetedValue, actual_value: item.actualValue, occurred_on: item.occurredOn, evidence_url: item.evidenceUrl, created_by: user.id }).select().single(); if (result.error) return Response.json({ error: result.error.message }, { status: 403 }); return Response.json(result.data, { status: 201 }); }
