import type { V2WorkspaceSnapshot } from "@/lib/v2/types";

export const v2DemoSnapshot: V2WorkspaceSnapshot = {
  workspaceName: "Enterprise Lookout",
  currentUser: "Sebastián",
  teammates: ["José Miguel"],
  aiBudget: { spentUsd: 1.82, limitUsd: 5 },
  projects: [
    {
      id: "asado-dieciocho",
      name: "Asado 18 de septiembre",
      institution: "Universidad Católica",
      ownerName: "Sebastián",
      accessMode: "shared",
      status: "active",
      goal: 2500000,
      committed: 1180000,
      received: 720000,
      companies: 18,
      nextAction: "Aprobar investigación de 4 marcas",
      eventDate: "2026-09-18",
    },
    {
      id: "pastoral-invierno-2026",
      name: "Pastoral Invierno 2026",
      institution: "Pastoral UC",
      ownerName: "José Miguel",
      accessMode: "personal",
      status: "active",
      goal: 6000000,
      committed: 3900000,
      received: 3200000,
      companies: 42,
      nextAction: "Responder a Soprole",
      eventDate: "2026-07-20",
    },
    {
      id: "bienvenida-novatos",
      name: "Bienvenida novatos 2027",
      institution: "FEUC",
      ownerName: "Sebastián",
      accessMode: "personal",
      status: "draft",
      goal: 4000000,
      committed: 0,
      received: 0,
      companies: 0,
      nextAction: "Completar brief del proyecto",
      eventDate: null,
    },
  ],
  companies: [
    {
      id: "pf-alimentos",
      name: "PF Alimentos",
      domain: "pfalimentos.cl",
      industry: "Alimentos",
      fitScore: 94,
      factStatus: "verified",
      projectNames: ["Asado 18 de septiembre"],
      contactName: "Carolina Muñoz",
      contactQuality: "verificado",
      nextAction: "Revisar informe profundo",
    },
    {
      id: "soprole",
      name: "Soprole",
      domain: "soprole.cl",
      industry: "Alimentos",
      fitScore: 89,
      factStatus: "confirmed",
      projectNames: ["Pastoral Invierno 2026", "Asado 18 de septiembre"],
      contactName: "Martín Silva",
      contactQuality: "respondió",
      nextAction: "Responder hoy",
    },
    {
      id: "la-preferencia",
      name: "La Preferida",
      domain: "lapreferida.cl",
      industry: "Alimentos",
      fitScore: 86,
      factStatus: "found",
      projectNames: ["Asado 18 de septiembre"],
      contactName: "Daniela Rojas",
      contactQuality: "encontrado",
      nextAction: "Verificar rol y correo",
    },
    {
      id: "ccu",
      name: "CCU",
      domain: "ccu.cl",
      industry: "Bebidas",
      fitScore: 78,
      factStatus: "verified",
      projectNames: ["Pastoral Invierno 2026"],
      contactName: null,
      contactQuality: "sin contacto",
      nextAction: "Buscar contacto de asuntos corporativos",
    },
  ],
  contacts: [
    {
      id: "carolina-munoz",
      name: "Carolina Muñoz",
      company: "PF Alimentos",
      role: "Jefa de Marketing Regional",
      email: "carolina@pfalimentos.cl",
      phone: null,
      quality: "verificado",
      evidence: "Sitio oficial · 8 ago 2026",
      lastInteraction: "Sin interacción",
    },
    {
      id: "martin-silva",
      name: "Martín Silva",
      company: "Soprole",
      role: "Asuntos Corporativos",
      email: "martin@soprole.cl",
      phone: "+56 9 •••• 1842",
      quality: "respondió",
      evidence: "Respuesta Gmail · 9 ago 2026",
      lastInteraction: "Hoy, 09:42",
    },
    {
      id: "daniela-rojas",
      name: "Daniela Rojas",
      company: "La Preferida",
      role: "Marketing",
      email: "daniela@lapreferida.cl",
      phone: null,
      quality: "encontrado",
      evidence: "Fuente pública · 8 ago 2026",
      lastInteraction: "Sin interacción",
    },
  ],
  threads: [
    {
      id: "thread-soprole",
      account: "sebastian@uc.cl",
      provider: "microsoft",
      company: "Soprole",
      contact: "Martín Silva",
      subject: "Colaboración Pastoral Invierno 2026",
      snippet: "Gracias por escribirnos. Podemos revisar una colaboración en productos…",
      receivedAt: "Hoy, 09:42",
      unread: true,
      project: "Pastoral Invierno 2026",
      messages: [
        {
          direction: "outbound",
          author: "Sebastián",
          date: "7 ago, 16:18",
          body: "Hola Martín, estamos organizando Pastoral Invierno 2026 y nos gustaría explorar una colaboración de productos para las actividades con estudiantes.",
        },
        {
          direction: "inbound",
          author: "Martín Silva",
          date: "Hoy, 09:42",
          body: "Hola Sebastián, gracias por escribirnos. Podemos revisar una colaboración en productos. ¿Cuántos estudiantes participan y qué fechas manejan?",
        },
      ],
      advice: [
        "Responder las dos preguntas antes de volver a presentar la propuesta.",
        "Diferenciar asistentes totales de beneficiarios directos.",
        "No prometer exclusividad: todavía no está aprobada.",
      ],
      suggestedReply: "Hola Martín, muchas gracias por responder. Estimamos 180 estudiantes participantes y las actividades se realizarán entre el 20 y el 24 de julio. Podemos compartirte el desglose por jornada y una propuesta concreta de visibilidad para Soprole. ¿Te sirve que te la envíe durante hoy?\n\nSaludos,\nSebastián",
    },
    {
      id: "thread-pf",
      account: "colaboraciones@uc.cl",
      provider: "gmail",
      company: "PF Alimentos",
      contact: "Carolina Muñoz",
      subject: "Asado universitario · 18 de septiembre",
      snippet: "Borrador inicial pendiente de aprobación",
      receivedAt: "Ayer",
      unread: false,
      project: "Asado 18 de septiembre",
      messages: [],
      advice: ["El contacto está verificado, pero todavía no ha respondido."],
      suggestedReply: "Hola Carolina, soy Sebastián y estoy organizando un asado universitario para el 18 de septiembre. Esperamos cerca de 100 estudiantes y estamos buscando una marca de alimentos que quiera participar con productos. A cambio podemos ofrecer presencia visible durante la actividad y difusión en nuestros canales. ¿Te parece si te envío una propuesta breve con cantidades y alternativas de colaboración?",
      draftStatus: "draft",
    },
  ],
  attention: [
    {
      id: "reply-soprole",
      kind: "reply",
      title: "Soprole respondió",
      detail: "Pide cantidad de alumnos y fechas antes de evaluar el aporte.",
      project: "Pastoral Invierno 2026",
      owner: "José Miguel",
      due: "Hoy",
      href: "/mail?thread=thread-soprole",
    },
    {
      id: "research-sausages",
      kind: "research",
      title: "4 candidatos listos para aprobar",
      detail: "PF Alimentos, La Preferida, Llanquihue y Winter.",
      project: "Asado 18 de septiembre",
      owner: "Sebastián",
      due: "Hoy",
      href: "/projects/asado-dieciocho?tab=research",
    },
    {
      id: "drafts-three",
      kind: "approval",
      title: "3 primeros correos por revisar",
      detail: "Ninguno se enviará sin tu aprobación explícita.",
      project: "Asado 18 de septiembre",
      owner: "Sebastián",
      due: "Hoy",
      href: "/mail?filter=drafts",
    },
    {
      id: "followup-ccu",
      kind: "followup",
      title: "Follow-up sugerido para CCU",
      detail: "Han pasado 9 días. Se creará solamente como borrador.",
      project: "Pastoral Invierno 2026",
      owner: "José Miguel",
      due: "Mañana",
      href: "/mail?filter=followups",
    },
  ],
};
